routes/web.php
<?php

use App\Http\Controllers\AnggotaController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ApplyController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\AngsuranController;
use App\Http\Controllers\PengambilanController;
use App\Http\Controllers\SimpananController;

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/

Route::get('login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('login', [LoginController::class, 'authenticate']);
Route::post('logout', [LoginController::class, 'logout']);
Route::resource('register', RegisterController::class)->middleware('guest');
Route::get('dashboard', [DashboardController::class, 'index'])->middleware('auth');
Route::middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');
});

Route::get('/home', function () {
    return view('user.home', [
        "title" => "home"
    ]);
});

Route::get('/about', function () {
    return view('user.about', [
        "title" => "about"
    ]);
});

Route::get('/services', function () {
    return view(
        'user.services',
        [
            "title" => "services"
        ]
    );
});

Route::resource('apply', ApplyController::class)->middleware('auth');


Route::get('simpanan',[ApplyController::class, 'simpanan'])->name('simpanan')->middleware('auth');
Route::post('simpan',[ApplyController::class, 'simpan'])->name('simpan')->middleware('auth');

Route::get('penarikan',[ApplyController::class, 'penarikan'])->name('penarikan')->middleware('auth');
Route::post('tarik',[ApplyController::class, 'tarik'])->name('tarik')->middleware('auth');

Route::get('angsuran',[ApplyController::class, 'angsuran'])->name('angsuran')->middleware('auth');
Route::post('angsur',[ApplyController::class, 'angsur'])->name('angsur')->middleware('auth');

Route::get('/contact', function () {
    return view('user.contact', [
        "title" => "contact"
    ]);
});

Route::resource('account', AccountController::class)->middleware('auth');
Route::post('change', [AccountController::class, 'change'])->name('change')->middleware('auth');

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::resource('anggota', AnggotaController::class)->middleware('auth');
Route::get('cetak-anggota', [AnggotaController::class, 'cetak'])->name('cetak-anggota')->middleware('auth');

Route::resource('deposit', SimpananController::class)->middleware('auth');
Route::get('cetak-simpanan', [SimpananController::class, 'cetak'])->name('cetak-simpanan')->middleware('auth');

Route::resource('pengambilan', PengambilanController::class)->middleware('auth');
Route::get('cetak-pengambilan', [PengambilanController::class, 'cetak'])->name('cetak-pengambilan')->middleware('auth');

Route::resource('peminjaman', PeminjamanController::class)->middleware('auth');
Route::get('cetak-peminjaman', [PeminjamanController::class, 'cetak'])->name('cetak-peminjaman')->middleware('auth');

Route::resource('cicilan', AngsuranController::class)->middleware('auth');
Route::get('cetak-angsuran', [AngsuranController::class, 'cetak'])->name('cetak-angsuran')->middleware('auth');

resources/views/admin/anggota.blade.php
@extends('layouts.admin')

@section('container')
        <!-- Table Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-12">
                        <div class="bg-light rounded h-100 p-4">
                        <h4 class="mt-4 mb-4"><b>Tabel Anggota</b></h4>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">ID Anggota</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Username</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">No Telp</th>
                                        <th scope="col">Alamat</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach ($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->username }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->no_telp }}</td>
                                    <td>{{ $user->alamat }}</td>

                                    <td>
                                    <a class="btn btn-info" href="/anggota/{{ $user->id }}">Show</a>
                                    <a class="btn btn-primary" href="/anggota/{{ $user->id }}/edit">Edit</a>
                                    <form action="/anggota/{{ $user->id }}" method="POST" class="d-inline">
                                        @method('delete')
                                        @csrf 
                                        <button class="btn btn-danger" onclick="return confirm('Anda yakin?')">Delete</button>
                                    </form>
                                    </td>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <a class="btn btn-success" href="{{ route('cetak-anggota') }}"><i class="fa fa-print"></i> Cetak Laporan</a>
                        </div>
                    </div>
                </div>
            </div>
        <!-- Table End -->
        <!-- Edit Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header d-flex justify-content-center">
                        <h5 class="modal-title" id="exampleModalLabel"><b>Edit Data</b></h5>
                    </div>
                    <div class="modal-body">
                        <form action="/anggota" method="POST">
                            
                            @csrf
                            <div class="form-group">
                                <label for="name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{ $user->name }}" required>
                            </div>
                            <div class="form-group">
                                <label for="username" class="col-form-label">Username:</label>
                                <input type="text" class="form-control" id="username" name="username" value="{{ $user->username }}" required>
                            </div>
                            <div class="form-group">
                                <label for="email" class="col-form-label">Email:</label>
                                <input type="text" class="form-control" id="email" name="email" value="{{ $user->email }}" required>
                            </div>

                            <div class="form-group">
                                <label for="password" class="col-form-label">Password:</label>
                                <input type="text" class="form-control" id="password" name="password" required>
                            </div>
                        
                            <div class="form-outline mb-4">
                                <label for="no_telp" class="col-form-label">No Telp:</label>
                            <input type="number" id="no_telp" name="no_telp" class="form-control" value="{{ $user->no_telp }}" required>
                            </div>

                            <div class="form-outline mb-4">
                                <label for="alamat" class="col-form-label">Alamat:</label>  
                            <input type="text" id="alamat" name="alamat" class="form-control" value="{{ $user->alamat }}" required>
                            </div>
                        
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        </form>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/admin/angsuran.blade.php
@extends('layouts.admin')

@section('container')
        <!-- Table Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-12">
                        <div class="bg-light rounded h-100 p-4">
                            <h4 class="mt-4 mb-4"><b>Tabel Angsuran</b></h4>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">ID Angsuran</th>
                                        <th scope="col">Tanggal Angsur</th>
                                        <th scope="col">Nama Pengangsur</th>
                                        <th scope="col">Jumlah</th>
                                        <th scope="col">Sisa Peminjaman</th>
                                        <th scope="col">Sisa Tenggat Waktu</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                
                                @foreach ($angsuran as $angsur)
                                <tr>
                                    <td>{{ $angsur->id_angsuran }}</td>
                                    <td>{{ $angsur->tgl_angsur }}</td>
                                    <td>{{ $angsur->users->name }}</td>
                                    <td>{{ $angsur->jumlah }}</td>
                                    <td>{{ $angsur->jumlah_sisa }}</td>
                                    <td>{{ $angsur->sisa_tenggat_waktu }}</td>
                                    <td>
                                    <a class="btn btn-info" href="/angsuran/{{ $angsur->id_angsuran }}">Show</a>
                                    <a class="btn btn-primary" href="/angsuran/{{ $angsur->id_angsuran }}/edit">Edit</a>
                                    <form action="/angsuran/{{ $angsur->id_angsuran }}" method="POST" class="d-inline">
                                        @method('delete')
                                        @csrf 
                                        <button class="btn btn-danger" onclick="return confirm('Anda yakin?')">Delete</button>
                                    </form>
                                    </td>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <a class="btn btn-success" href="{{ route('cetak-angsuran') }}"><i class="fa fa-print"></i> Cetak Laporan</a>  
                        </div>
                    </div>
                </div>
            </div>
        <!-- Table End -->
@endsection

resources/views/admin/cetak-anggota.blade.php
@extends('layouts.edit-admin')
 
@section('content')
    <div class="row"> 
        <div class="col-lg-12 margin-tb">
            <div class="pull-left mt-2">
                <h5 class="text-center">KOPERASI SIMPAN PINJAM</h5>
                <h4 class="text-center">LAPORAN ANGGOTA KOPERASI</h4>
                
                <div class="text-left">
                    <p><b>ADMIN</b></p>
                    <p><b>Nama : </b>{{ auth()->user()->name }}</p>
                    <p><b>ID   : </b>{{ auth()->user()->id }}</p>
                    
                </div>
            </div>
        </div>
    </div>
   
    <table class="table table-bordered">
            <tr>
            <th scope="col">ID Anggota</th>
            <th scope="col">Name</th>
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col">No Telp</th>
            <th scope="col">Alamat</th>
            </tr>
            @foreach ($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->username }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->no_telp }}</td>
                    <td>{{ $user->alamat }}</td>
                </tr>
            @endforeach
        </table>
@endsection 

resources/views/admin/cetak-peminjaman.blade.php
@extends('layouts.edit-admin')
 
@section('content')
    <div class="row"> 
        <div class="col-lg-12 margin-tb">
            <div class="pull-left mt-2">
                <h5 class="text-center">KOPERASI SIMPAN PINJAM</h5>
                <h4 class="text-center">LAPORAN PEMINJAMAN</h4>
                
                <div class="text-left">
                    <p><b>ADMIN</b></p>
                    <p><b>Nama : </b>{{ auth()->user()->name }}</p>
                    <p><b>ID   : </b>{{ auth()->user()->id }}</p>
                    
                </div>
            </div>
        </div>
    </div>
   
    <table class="table table-bordered">
            <tr>
                <th scope="col">ID Peminjaman</th>
                <th scope="col">Tanggal Pinjam</th>
                <th scope="col">Nama Peminjam</th>
                <th scope="col">Jumlah</th>
                <th scope="col">Tenggat Waktu</th>
            </tr>
            @foreach ($peminjaman as $pinjam)
                <tr>
                    <td>{{ $pinjam->id_peminjaman }}</td>
                    <td>{{ $pinjam->tgl_pinjam }}</td>
                    <td>{{ $pinjam->users->name }}</td>
                    <td>{{ $pinjam->jumlah }}</td>
                    <td>{{ $pinjam->tenggat_waktu }}</td>
                </tr>
            @endforeach
        </table>
@endsection 

resources/views/admin/cetak-pengambilan.blade.php
@extends('layouts.edit-admin')
 
@section('content')
    <div class="row"> 
        <div class="col-lg-12 margin-tb">
            <div class="pull-left mt-2">
                <h5 class="text-center">KOPERASI SIMPAN PINJAM</h5>
                <h4 class="text-center">LAPORAN PENARIKAN</h4>
                
                <div class="text-left">
                    <p><b>ADMIN</b></p>
                    <p><b>Nama : </b>{{ auth()->user()->name }}</p>
                    <p><b>ID   : </b>{{ auth()->user()->id }}</p>
                    
                </div>
            </div>
        </div>
    </div>
   
    <table class="table table-bordered">
            <tr>
            <th scope="col">ID Penarikan</th>
            <th scope="col">Tanggal Penarikan</th>
            <th scope="col">Nama Penarik</th>
            <th scope="col">Jumlah</th>
            <th scope="col">Saldo</th>
            </tr>
            @foreach ($pengambilan as $ambil)
                <tr>
                    <td>{{ $ambil->id_pengambilan }}</td>
                    <td>{{ $ambil->tgl_ambil }}</td>
                    <td>{{ $ambil->users->name }}</td>
                    <td>{{ $ambil->jumlah }}</td>
                    <td>{{ $ambil->saldo }}</td>
                </tr>
            @endforeach
        </table>
@endsection 

resources/views/admin/cetak-simpanan.blade.php
@extends('layouts.edit-admin')
 
@section('content')
    <div class="row"> 
        <div class="col-lg-12 margin-tb">
            <div class="pull-left mt-2">
                <h5 class="text-center">KOPERASI SIMPAN PINJAM</h5>
                <h4 class="text-center">LAPORAN SIMPANAN</h4>
                
                <div class="text-left">
                    <p><b>ADMIN</b></p>
                    <p><b>Nama : </b>{{ auth()->user()->name }}</p>
                    <p><b>ID   : </b>{{ auth()->user()->id }}</p>
                    
                </div>
            </div>
        </div>
    </div>
   
    <table class="table table-bordered">
            <tr>
            <th scope="col">ID Simpanan</th>
            <th scope="col">Tanggal Simpan</th>
            <th scope="col">Nama Penyimpan</th>
            <th scope="col">Jumlah</th>
            <th scope="col">Saldo</th>
            </tr>
            @foreach ($simpanan as $simpan)
                <tr>
                    <td>{{ $simpan->id_simpanan }}</td>
                    <td>{{ $simpan->tgl_simpan }}</td>
                    <td>{{ $simpan->users->name }}</td>
                    <td>{{ $simpan->jumlah }}</td>
                    <td>{{ $simpan->saldo }}</td>
                </tr>
            @endforeach
        </table>
@endsection 

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('container')

            <!-- Sale & Revenue Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-6 col-xl-6">
                        <div class="bg-light rounded d-flex align-items-center justify-content-between p-4 dashboard-info" style="background: linear-gradient(135deg, #17ead9 0%, #6078ea 100%); height: 8em">
                            <i class="fa fa-user fa-3x text-light"></i>
                            <div class="ms-1">
                                <p class="mb-2 text-light fw-bold">Total Anggota</p>
                                <h4 class="mb-0 text-light fw-bold">{{ auth()->user()->count() - 1 }}</h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xl-6">
                        <div class="bg-light rounded d-flex align-items-center justify-content-between p-4 dashboard-info" style="background: linear-gradient(135deg, #17ead9 0%, #6078ea 100%); height: 8em">
                            <i class="fa fa-credit-card fa-3x text-light"></i>
                            <div class="ms-2">
                                <p class="mb-2 text-light fw-bold">Total Peminjaman</p>
                                <h4 class="mb-0 text-light fw-bold">$100000</h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xl-6">
                        <div class="bg-light rounded d-flex align-items-center justify-content-between p-4 dashboard-info" style="background: linear-gradient(135deg, #17ead9 0%, #6078ea 100%); height: 8em">
                            <i class="fa fa-university fa-3x text-light"></i>
                            <div class="ms-3">
                                <p class="mb-2 text-light ">Total Simpanan</p>
                                <h6 class="mb-0 text-light fw-bold">$1234</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xl-6">
                        <div class="bg-light rounded d-flex align-items-center justify-content-between p-4 dashboard-info" style="background: linear-gradient(135deg, #17ead9 0%, #6078ea 100%); height: 8em">
                            <i class="fa fa-calculator fa-3x text-light"></i>
                            <div class="ms-3">
                                <p class="mb-2 text-light ">Total Penarikan</p>
                                <h6 class="mb-0 text-light fw-bold">$1234</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Sale & Revenue End -->


            <!-- Widgets Start -->
            <div class="container-fluid pt-4 px-4 mb-5">
                <div class="row g-4 d-flex justify-content-center">
                    <div class="col-sm-12 col-md-6 col-xl-5">
                        <div class="h-100 bg-light rounded p-4">
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h6 class="mb-0">Calender</h6>
                                <a href="">Show All</a>
                            </div>
                            <div id="calender"></div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6 col-xl-5">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Progress Bar</h6>
                            <div class="pg-bar mb-3">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-striped bg-success" role="progressbar"
                                        aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                            <div class="pg-bar mb-3">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-striped bg-info" role="progressbar"
                                        aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                            <div class="pg-bar mb-3">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-striped bg-warning" role="progressbar"
                                        aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                            <div class="pg-bar mb-0">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-striped bg-danger" role="progressbar"
                                        aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Widgets End -->
@endsection

resources/views/admin/edit-peminjaman.blade.php
@extends('layouts.admin')

@section('container')
        <!-- Table Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-12">
                        <div class="bg-light rounded h-100 p-4">
                        
                        <div class="navbar-nav w-100">
                            <a href="/peminjaman" class="nav-item nav-link"><i class="fa fa-arrow-left me-2"></i></a>
                        </div>

                        <div class="row justify-content-center align-items-center">
                            <div class="card pt-4 pb-3 mb-3" style="width: 60%;">
                            
                                <div class="card-header">
                                    <h5 class="text-center mb-3"><b>Edit Peminjaman</b></h5>
                                </div>
                            
                            <div class="card-body">
                                <form action="{{ route('peminjaman.update', $peminjaman->id_peminjaman) }}" method="POST">
                                @method('put')
                                @csrf
                                <div class="form-group">
                                    <label for="tgl_pinjam" class="col-form-label">Tanggal Pinjam:</label>
                                    <input type="date" class="form-control" id="tgl_pinjam" name="tgl_pinjam" value="{{ $peminjaman->tgl_pinjam }}" required>
                                </div>
                                <div class="form-group">
                                    <label for="user_id" class="col-form-label">ID Peminjam:</label>
                                    <input type="text" class="form-control" id="user_id" name="user_id" value="{{ $peminjaman->users->id }}" required>
                                </div>
                                <div class="form-group">
                                    <label for="jumlah" class="col-form-label">Jumlah:</label>
                                    <input type="number" class="form-control" id="jumlah" name="jumlah" value="{{ $peminjaman->jumlah }}" required>
                                </div>

                                <div class="form-group">
                                    <label for="tenggat_waktu" class="col-form-label">Tenggat Waktu:</label>
                                    <input type="date" class="form-control" id="tenggat_waktu" name="tenggat_waktu" value="{{ $peminjaman->tenggat_waktu }}" required>
                                </div>
                            </div>
                            
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                                </form>
                            </div>
                            
                            </div> 
                        </div>

                        </div>
                    </div>
                </div>
            </div>
        <!-- Table End -->
=======
@extends('layouts.edit-admin')

@section('container')
<form>
    <h4 class="fw-bolder text-center">Edit Peminjaman</h4>
    <div class="form-group">
        <label for="tgl_pinjam" class="col-form-label">Tanggal Pinjam:</label>
        <input type="date" class="form-control" id="tgl_pinjam" name="tgl_pinjam" value="{{ $pinjam->tgl_pinjam }}" required>
    </div>
    <div class="form-group">
        <label for="user_id" class="col-form-label">ID Peminjam:</label>
        <input type="text" class="form-control" id="user_id" name="user_id" value="{{ $pinjam->users->id }}" required>
    </div>
    <div class="form-group">
        <label for="jumlah" class="col-form-label">Jumlah:</label>
        <input type="number" class="form-control" id="jumlah" name="jumlah" value="{{ $pinjam->jumlah }}" required>
    </div>

    <div class="form-group">
        <label for="tenggat_waktu" class="col-form-label">Tenggat Waktu:</label>
        <input type="date" class="form-control" id="tenggat_waktu" name="tenggat_waktu" value="{{ $pinjam->tenggat_waktu }}" required>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

resources/views/admin/edit-pengambilan.blade.php
@extends('layouts.admin')

@section('container')
        <!-- Table Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-12">
                        <div class="bg-light rounded h-100 p-4">
                        
                        <div class="navbar-nav w-100">
                            <a href="/pengambilan" class="nav-item nav-link"><i class="fa fa-arrow-left me-2"></i></a>
                        </div>

                        <div class="row justify-content-center align-items-center">
                            <div class="card pt-4 pb-3 mb-3" style="width: 60%;">
                            
                                <div class="card-header">
                                    <h5 class="text-center mb-3"><b>Edit Simpanan</b></h5>
                                </div>
                            
                            <div class="card-body">
                                <form action="{{ route('pengambilan.update', $pengambilan->id_pengambilan) }}" method="POST">
                                @method('put')
                                @csrf
                                <div class="form-group">
                                    <label for="tgl_ambil" class="col-form-label">Tanggal Simpan:</label>
                                    <input type="date" class="form-control" id="tgl_ambil" name="tgl_ambil" value="{{ $pengambilan->tgl_ambil }}" required>
                                </div>
                                <div class="form-group">
                                    <label for="user_id" class="col-form-label">ID Peminjam:</label>
                                    <input type="text" class="form-control" id="user_id" name="user_id" value="{{ $pengambilan->users->id }}" required>
                                </div>
                                <div class="form-group">
                                    <label for="jumlah" class="col-form-label">Jumlah:</label>
                                    <input type="number" class="form-control" id="jumlah" name="jumlah" value="{{ $pengambilan->jumlah }}" required>
                                </div>

                                <div class="form-group">
                                    <label for="saldo" class="col-form-label">Saldo:</label>
                                    <input type="date" class="form-control" id="saldo" name="saldo" value="{{ $pengambilan->saldo }}" required>
                                </div>
                            </div>
                            
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                                </form>
                            </div>
                            
                            </div> 
                        </div>

                        </div>
                    </div>
                </div>
            </div>
        <!-- Table End -->
@endsection