routes/web.php
<?php

use App\Http\Controllers\AnggotaController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ApplyController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\AngsuranController;
use App\Http\Controllers\PengambilanController;
use App\Http\Controllers\SimpananController;

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/

Route::get('login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('login', [LoginController::class, 'authenticate']);
Route::post('logout', [LoginController::class, 'logout']);
Route::resource('register', RegisterController::class)->middleware('guest');
Route::get('dashboard', [DashboardController::class, 'index'])->middleware('auth');
Route::middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');
});

Route::get('/home', function () {
    return view('user.home', [
        "title" => "home"
    ]);
});

Route::get('/about', function () {
    return view('user.about', [
        "title" => "about"
    ]);
});

Route::get('/services', function () {
    return view(
        'user.services',
        [
            "title" => "services"
        ]
    );
});

Route::resource('apply', ApplyController::class)->middleware('auth');


Route::get('simpanan',[ApplyController::class, 'simpanan'])->name('simpanan')->middleware('auth');
Route::post('simpan',[ApplyController::class, 'simpan'])->name('simpan')->middleware('auth');

Route::get('penarikan',[ApplyController::class, 'penarikan'])->name('penarikan')->middleware('auth');
Route::post('tarik',[ApplyController::class, 'tarik'])->name('tarik')->middleware('auth');

Route::get('angsuran',[ApplyController::class, 'angsuran'])->name('angsuran')->middleware('auth');
Route::post('angsur',[ApplyController::class, 'angsur'])->name('angsur')->middleware('auth');

Route::get('/contact', function () {
    return view('user.contact', [
        "title" => "contact"
    ]);
});

Route::resource('account', AccountController::class)->middleware('auth');
Route::post('change', [AccountController::class, 'change'])->name('change')->middleware('auth');

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::resource('anggota', AnggotaController::class)->middleware('auth');
Route::get('cetak-anggota', [AnggotaController::class, 'cetak'])->name('cetak-anggota')->middleware('auth');

Route::resource('deposit', SimpananController::class)->middleware('auth');
Route::get('cetak-simpanan', [SimpananController::class, 'cetak'])->name('cetak-simpanan')->middleware('auth');

Route::resource('pengambilan', PengambilanController::class)->middleware('auth');
Route::get('cetak-pengambilan', [PengambilanController::class, 'cetak'])->name('cetak-pengambilan')->middleware('auth');

Route::resource('peminjaman', PeminjamanController::class)->middleware('auth');
Route::get('cetak-peminjaman', [PeminjamanController::class, 'cetak'])->name('cetak-peminjaman')->middleware('auth');

Route::resource('cicilan', AngsuranController::class)->middleware('auth');
Route::get('cetak-angsuran', [AngsuranController::class, 'cetak'])->name('cetak-angsuran')->middleware('auth');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $table = 'users';
    protected $primaryKey = 'id';
    
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
        'no_telp',
        'alamat'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function simpanan(){
        return $this->hasMany(Simpanan::class, 'user_id', 'id');
    }

    public function pengambilan(){
        return $this->hasMany(Pengambilan::class, 'user_id', 'id');
    }

    public function peminjaman(){
        return $this->hasMany(Peminjaman::class, 'user_id', 'id');
    }

    public function angsuran(){
        return $this->hasMany(Angsuran::class, 'user_id', 'id');
    }
}

resources/views/user/about.blade.php
@extends('layouts.main')

@section('container')
<!-- Hero Start-->
<div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center ">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center pt-50">
                            <h2>About us</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Hero End -->
        <!-- About Law Start-->
        <div class="about-low-area section-padding2">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-12">
                        <div class="about-caption mb-50">
                            <!-- Section Tittle -->
                            <div class="section-tittle mb-35">
                                <span>Tentang Perusahaan Kami</span>
                                <h2>Siap Membantu Masalah Finansial Anda.</h2>
                            </div>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, oeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut eniminixm, quis nostrud exercitation ullamco laboris nisi ut aliquip exeaoauat. Duis aute irure dolor in reprehe.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, oeiusmod tempor incididunt ut labore et dolore magna aliq.</p>
                            <a href="apply.html" class="btn">Ajukan Peminjaman</a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12">
                        <!-- about-img -->
                        <div class="about-img ">
                            <div class="about-font-img d-none d-lg-block">
                                <img src="{{ asset('style/assets/img/gallery/about2.png') }}" alt="">
                            </div>
                            <div class="about-back-img ">
                                <img src="{{ asset('style/assets/img/gallery/about1.png') }}" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- About Law End-->
        <!-- Testimonial Start -->
        <div class="testimonial-area t-bg testimonial-padding">
            <div class="container ">
               <div class="row d-flex justify-content-center">
                    <div class="col-xl-11 col-lg-11 col-md-9">
                        <div class="h1-testimonial-active">
                            <!-- Single Testimonial -->
                            <div class="single-testimonial text-center">
                                 <!-- Testimonial Content -->
                                <div class="testimonial-caption ">
                                    <div class="testimonial-top-cap">
                                        <img src="{{ asset('style/assets/img/gallery/testimonial.png') }}" alt="">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, quo. Atque dolorem ab distinctio fugiat autem accusantium neque repellat nostrum.</p>
                                    </div>
                                    <!-- founder -->
                                    <div class="testimonial-founder d-flex align-items-center justify-content-center">
                                        <div class="founder-img">
                                            <img src="{{ asset('assets/img/testmonial/Homepage_testi.png') }}" alt="">
                                        </div>
                                       <div class="founder-text">
                                            <span>Pudidi</span>
                                            <p>Customer</p>
                                       </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Single Testimonial -->
                            <div class="single-testimonial text-center">
                                 <!-- Testimonial Content -->
                                <div class="testimonial-caption ">
                                    <div class="testimonial-top-cap">
                                        <img src="{{ asset('style/assets/img/gallery/testimonial.png') }}" alt="">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore facilis, aliquam ea similique nam odio id, amet deserunt a ducimus, repellendus nesciunt reiciendis ut esse nobis. Aliquid perferendis dolores corporis.</p>
                                    </div>
                                    <!-- founder -->
                                    <div class="testimonial-founder d-flex align-items-center justify-content-center">
                                        <div class="founder-img">
                                            <img src="{{ asset('assets/img/testmonial/Homepage_testi.png') }}" alt="">
                                        </div>
                                       <div class="founder-text">
                                            <span>Paidi</span>
                                            <p>Customer</p>
                                       </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
               </div>
            </div>
        </div>
        <!-- Testimonial End -->
        <!--Team Ara Start -->
        <div class="team-area section-padding30">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="cl-xl-7 col-lg-8 col-md-10">
                        <!-- Section Tittle -->
                        <div class="section-tittle text-center mb-70">
                            <span>Anngota Kami</span>
                            <h2>Ini Merupakan Beberapa Anggota Kami.</h2>
                        </div> 
                    </div>
                </div>
                <div class="row">
                <div class="col-lg-1 col-md-4 col-sm-6"></div>
                    <div class="col-lg-2 col-md-4 col-sm-6">
                        <div class="single-team mb-30">
                            <div class="team-img">
                                <img src="{{ asset('style/assets/img/gallery/home_blog2.png') }}" alt="">
                                <!-- Blog Social -->
                                <div class="team-social">
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fas fa-globe"></i></a></li>
                                </div>
                            </div>
                            <div class="team-caption">
                                <h3><a href="#">Kevin Natanael</a></h3>
                                <p>Founder</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-6">
                        <div class="single-team mb-30">
                            <div class="team-img">
                                <img src="{{ asset('style/assets/img/gallery/home_blog2.png') }}" alt="">
                                <!-- Blog Social -->
                                <div class="team-social">
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fas fa-globe"></i></a></li>
                                </div>
                            </div>
                            <div class="team-caption">
                                <h3><a href="#">Maulana Rosandy</a></h3>
                                <p>Founder</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-6">
                        <div class="single-team mb-30">
                            <div class="team-img">
                                <img src="{{ asset('style/assets/img/gallery/home_blog2.png') }}" alt="">
                                <!-- Blog Social -->
                                <div class="team-social">
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fas fa-globe"></i></a></li>
                                </div>
                            </div>
                            <div class="team-caption">
                                <h3><a href="#">Raditya Catur Narendra</a></h3>
                                <p>Founder</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-6">
                        <div class="single-team mb-30">
                            <div class="team-img">
                                <img src="{{ asset('style/assets/img/gallery/home_blog2.png') }}" alt="">
                                <!-- Blog Social -->
                                <div class="team-social">
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fas fa-globe"></i></a></li>
                                </div>
                            </div>
                            <div class="team-caption">
                                <h3><a href="#">Rofika Nur 'Aini</a></h3>
                                <p>Founder</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-6">
                        <div class="single-team mb-30">
                            <div class="team-img">
                                <img src="{{ asset('style/assets/img/gallery/home_blog2.png') }}" alt="">
                                <!-- Blog Social -->
                                <div class="team-social">
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fas fa-globe"></i></a></li>
                                </div>
                            </div>
                            <div class="team-caption">
                                <h3><a href="#">Rofiqoh Wahyuningtyas</a></h3>
                                <p>Founder</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-1 col-md-4 col-sm-6"></div>
                </div>
            </div>
        </div>
        <!-- Team Ara End -->
@endsection

resources/views/user/account.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Manage Account</title>

    {{-- CSS --}}
    <link rel="stylesheet" href="{{ asset('style/assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('style/assets/css/acount.css') }}">
</head>
    <body>
    <div class="hero-area2">
    
    <div class="container light-style flex-grow-1 container-p-y pt-4 pb-3">
        <div class="card overflow-hidden">
        <div class="row no-gutters row-bordered row-border-light">
            <div class="col-md-9">
                <div class="tab-content">
                    <div class="card-body">
                        <h5 class="font-weight-bold py-3 mb-0">Saldo Transaksi</h5>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Simpanan</th>
                                        <th scope="col">Penarikan</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Rp.</td>
                                        <td>Rp.</td>
                                    </tr>
                            </tbody>
                        </table>
                        <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Pinjaman</th>
                                        <th scope="col">Angsuran</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Rp.</td>
                                        <td>Rp.</td>
                                    </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
        @if(session()->has('success'))
            <div class="alert alert-success alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ session('success') }}
            </div>
        @endif
        <div class="container light-style flex-grow-1 container-p-y">
        <div class="card overflow-hidden">
        <div class="row no-gutters row-bordered row-border-light">
            <div class="col-md-9">
                <div class="tab-content">
                    <div class="tab-pane fade active show" id="account-general">
                        <h4 class="font-weight-bold py-3 mb-0 ml-3">Kelola Akun</h4>
                        <form method="post" action="{{ route('account.update', $users->id) }}" enctype="multipart/form-data">
                        @method('put')    
                        @csrf
                            <div class="card-body media align-items-center">
                                <input type="hidden" name="oldImage" value="{{ $users->image }}">
                                @if($users->image)
                                    <img src="{{ asset('storage/'.$users->image)}}" alt="" class="d-block ui-w-80">
                                @else
                                    <img alt="" class="d-block ui-w-80">
                                @endif
                                <div class="media-body ml-4">
                                <label class="btn btn-outline-primary">
                                    Upload Photo
                                    <input class="account-settings-fileinput" type="file" id="image" name="image">
                                </label> &nbsp;
                                <div class="text-light small mt-1">JPG or PNG</div>
                                </div>
                            </div>

                            <hr class="border-light m-0">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-label">Username</label>
                                            <input type="text" class="form-control mb-1" id="username" name="username" value="{{auth()->user()->username}}">
                                        </div>
                                        <div class="form-group">
                                            <label class="form-label">Email</label>
                                            <input type="text" class="form-control mb-1" id="email" name="email" value="{{auth()->user()->email}}">
                                        </div>
                                        <div class="form-group">
                                            <label class="form-label">Alamat</label>
                                            <input type="text" class="form-control" id="alamat" name="alamat" value="{{auth()->user()->alamat}}">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-label">Nama</label>
                                            <input type="text" class="form-control" id="name" name="name" value="{{auth()->user()->name}}">
                                        </div>
                                        <div class="form-group">
                                            <label class="form-label">No Telp</label>
                                            <input type="number" class="form-control" id="no_telp" name="no_telp" value="{{auth()->user()->no_telp}}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </div> 
                </div>
            </div>
        </div>
        </div>
            <div class="text-right mt-3">
                <button type="submit" class="btn btn-primary">Save Changes</button>&nbsp;
                </form>
                <a class="btn btn-outline-secondary" href="/account">Cancel</a>
            </div>
        </div>
        

        <div class="container light-style flex-grow-1 container-p-y pt-3">
            @if(session()->has('message'))
            <div class="alert alert-success alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ session('message') }}
            </div>
            @endif
        <div class="card overflow-hidden">
        <div class="row no-gutters row-bordered row-border-light">
            <div class="col-md-9">
                <div class="tab-content">
                    <div class="tab-pane fade active show" id="account-change-password">
                        <form method="post" action="{{ route('change') }}">
                        @csrf
                        <div class="card-body pt-0 pb-2">
                            <h4 class="font-weight-bold py-3 mb-0">Ubah Password</h4>
                            <div class="form-group">
                                <label class="form-label">Password Lama</label>
                                <input type="password" class="form-control" id="password_lama" name="password_lama">
                            </div>
                            <div class="form-group">
                                <label class="form-label">Password Baru</label>
                                <input type="password" class="form-control" id="password" name="password">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
            <div class="text-right mt-3">
                <button type="submit" class="btn btn-primary">Save Changes</button>&nbsp;
                <a class="btn btn-outline-secondary" href="/account">Cancel</a>
            </div>
            <div class="text-left mt-3 pb-4">
                <a class="btn btn-warning" href="/home">Back to Home</a>
            </div>
        </div>
    </form>
    </div>
    </body>
</html>

resources/views/user/angsuran.blade.php
@extends('layouts.main')

@section('container')

        <!-- Hero Start-->
        <div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center ">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center pt-50">
                            <h2>Apply Form</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Hero End -->
        @include('partials.apply')
        <!-- Apply Area Start -->
        <div class="apply-area pt-150 pb-150">
            <div class="container">
                <div class="row justify-content-center">

                    <div class="col-lg-8">
                        @if(session()->has('success'))
                        <div class="alert alert-success alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ session('success') }}
                        </div>
                        @endif
                        <div class="apply-wrapper">
                            <p>ANGSURAN</p>
                            <!-- Form -->
                            <form method="POST" action="{{ route('angsur') }}">
                                @csrf
                                <div class="row">
                                    <!-- ID Peminjam -->
                                    <div class="col-lg-6">
                                        <div class="single-form">
                                            <label>ID PENGANGSUR</label>
                                            <input type="text" id="user_id" name="user_id" value="{{ auth()->user()->id }}" readonly>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="single-form">
                                            <label></label>
                                            <input type="hidden" id="" name="">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="single-form">
                                            <label>* JUMLAH ANGSURAN</label>
                                            <input type="number" id="jumlah" name="jumlah">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="single-form">
                                            <label>SISA PEMINJAMAN</label>
                                            <input type="number" id="jumlah_sisa" name="jumlah_sisa" readonly>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="single-form">
                                            <label>* TANGGAL ANGSURAN</label>
                                            <input type="date" id="tgl_ambil" name="tgl_ambil">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="single-form">
                                            <label>SISA TENGGAT WAKTU</label>
                                            <input type="date" id="sisa_tenggat_waktu" name="sisa_tenggat_waktu" readonly>
                                        </div>
                                    </div>
                                </div>
                                <button class="btn apply-btn mt-30" type="submit">ANGSUR</button>
                            </form>
                            <!-- End From -->
                        </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Apply Area End -->
@endsection